run_name: WikiDiverse
seed: 43
pretrained_model: 'openai/clip-vit-base-patch32'
lr: 1e-5


data:
  num_entity: 132460
  kb_img_folder: /YOUR_PATH/WikiDiverse/kb_image
  mention_img_folder: /YOUR_PATH/WikiDiverse/mention_image
  qid2id: /YOUR_PATH/WikiDiverse/qid2id.json
  entity: /YOUR_PATH/WikiDiverse/kb_entity.json
  train_file: /YOUR_PATH/WikiDiverse/wiki_diverse_train.json
  dev_file: /YOUR_PATH/WikiDiverse/wiki_diverse_dev.json
  test_file: /YOUR_PATH/WikiDiverse/wiki_diverse_test.json

  batch_size: 256
  num_workers: 8
  text_max_length: 40

  eval_chunk_size: 6000
  eval_batch_size: 20
  embed_update_batch_size: 512


model:
  input_hidden_dim: 512
  input_image_hidden_dim: 768
  hidden_dim: 96

  dropout: 0.1
  ot_transport: 3
  ot_reg: 0.05



trainer:
  accelerator: 'gpu'
  devices: 1
  max_epochs: 20
  num_sanity_val_steps: 0
  check_val_every_n_epoch: 2
  log_every_n_steps: 30
